/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tulipa.engine;

import javax.swing.JFrame;
import javax.swing.JLabel;

import tulipa.engine.render.*;
import java.awt.*;

public class App 
{
    public static void main(String[] args) {
        
        Window window = new Window();
        GameRenderer render = new GameRenderer(window);

        float[] point1 = {0f, 0f};
        float[] point2 = {100f, 100f};

        window.drawLine(point1, point2, Color.BLUE);
    }
}
